# Generated by Django 5.0.13 on 2025-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_dog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="name",
            field=models.CharField(max_length=100, verbose_name="breed"),
        ),
    ]
